<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="USSI.API.db" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="USSI.API.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dbup" Version="5.0.41" />
    <PackageReference Include="dbup-sqlite" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Middleware\USSI.API.Core.DataServices\USSI.API.Core.DataServices.csproj" />
    <ProjectReference Include="..\..\Models\USSI.API.Models\USSI.API.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="InitDb\SQLFiles\CreateTemplateColumnTable.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="InitDb\SQLFiles\CreateTemplateTable.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
