CREATE TABLE IF NOT EXISTS "TemplateColumn" (
	"TemplateColumnID" INTEGER NOT NULL,
	"TemplateId" INTEGER NOT NULL,
	"Name" VARCHAR(150) NOT NULL,
	"DataType" VARCHAR(150) NOT NULL,
	"Required" INTEGER NOT NULL,
	PRIMARY KEY ("TemplateColumnID"),
	CONSTRAINT "0" FOREIGN KEY ("TemplateId") REFERENCES "Template" ("TemplateId") ON UPDATE NO ACTION ON DELETE NO ACTION
)
;
